library(rvest)
library(dplyr)
library(stringr)
library(robotstxt)
url <- 'https://companiesmarketcap.com/automakers/largest-automakers-by-market-cap/'
web <- read_html(url)
View(web)
name <- web %>% html_nodes('.company-name') %>% html_text()
View(name)
marketcap  <- web %>% html_nodes('.name-td+ .td-right') %>% html_text()
View(marketcap)
price  <- web %>% html_nodes('.td-right+ .td-right') %>% html_text()
View(price)
car=data.frame(name,marketcap,price)
View(car)
write.csv(car,"car.csv")
